function [fitresult, gof] = Example_Fit_Code2(degree, CC)
%CREATEFIT(DEGREE,CC)
%  Create a fit.
%  
%  Data for 'untitled fit 1' fit:
%      X Input : degree
%      Y Output: CC
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.
 
%  Auto-generated by MATLAB on 11-Sep-2020 15:06:11
 

%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( degree, CC );

% Set up fittype and options.
ft = fittype( 'a*x^(-1)', 'independent', 'x', 'dependent', 'y' );
excludedPoints = excludedata( xData, yData, 'Indices', 27 );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = 0.210925791610045;
opts.Exclude = excludedPoints;

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData, excludedPoints );
legend( h, 'CC vs. degree', 'Excluded CC vs. degree', 'untitled fit 1', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'degree', 'Interpreter', 'none' );
ylabel( 'CC', 'Interpreter', 'none' );
grid on


