function [fitresult, gof] = Fit_Function(distr_count, distr_rel)
%CREATEFIT(DISTR_COUNT,DISTR_REL)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : distr_count
%      Y Output: distr_rel
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 08-Sep-2020 11:31:33


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( distr_count, distr_rel );

% Set up fittype and options.

ft = fittype( 'power1' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [0.0255020108869648 0.308846682986109];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData );
legend( h, 'distr_rel vs. distr_count', 'untitled fit 1', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'distr_count', 'Interpreter', 'none' );
ylabel( 'distr_rel', 'Interpreter', 'none' );
grid on
end

